In [1]:
from mmdet.datasets import build_dataset
from mmdet.models import build_detector
from mmdet.apis import inference_detector, init_detector, show_result_pyplot
from mmcv import Config
import copy
import os.path as osp
import os
import mmcv
import numpy as np
import time
import cv2
import matplotlib.pyplot as plt
import matplotlib
from pylab import *
from matplotlib import cm

os.environ["CUDA_VISIBLE_DEVICES"]="0"

def sigmoid(x):
    # TODO: Implement sigmoid function
    return 1/(1 + np.exp(-x))

config_xiaohei='./configs/faster_rcnn/xiaohei_faster_rcnn_r50_fpn_1x_chenzhou.py'
config_faster='./configs/faster_rcnn/faster_rcnn_r50_fpn_1x_chenzhou.py'
config_mask='./configs/mask_rcnn/mask_rcnn_r50_fpn_1x_chenzhou.py'
config_ms='./configs/ms_rcnn/ms_rcnn_r50_fpn_1x_chenzhou.py'

work_xiaohei='logs/xiaohei_faster_rcnn_r50_fpn_1x_chenzhou_202011141101/'
work_faster='logs/faster_rcnn_r50_fpn_1x_chenzhou_202011260631/'
work_mask='logs/mask_rcnn_r50_fpn_1x_chenzhou_202011250925/'
work_ms='logs/ms_rcnn_r50_fpn_1x_chenzhou_202011251546/'

configDict = [
                ['xiaohei', config_xiaohei, work_xiaohei]
                ,['faster', config_faster, work_faster]
                ,['mask', config_mask, work_mask]
                ,['ms', config_ms, work_ms]
             ]

f = open('logs/processInference-Proposal.log', 'w+')

for config_type, config_file, work_dir in configDict:
    cfg = Config.fromfile(config_file)
    cfg.work_dir = work_dir
    cfg.seed = 0
    cfg.total_epochs = 50
    cfg.log_config.interval = 1000

    checkpoint = cfg.work_dir + 'epoch_12.pth'

    model = init_detector(cfg, checkpoint, device='cuda:0')
    datasets = [build_dataset(cfg.data.train)]
    model.CLASSES = datasets[0].CLASSES
    # validations
    result_path = cfg.work_dir + '/tests/'
    text=config_type + ':'
    # os.linesep代表当前操作系统上的换行符

    path = '/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/tests/'
    for root, dirs, files in os.walk(os.path.abspath(path)):
        for file in files:
            img = mmcv.imread(path + file)
            if 'mask_head' in cfg.model.roi_head:
                result, a, cls_score, bbox_pred = inference_detector(model, img)
            else:
                result, cls_score, bbox_pred = inference_detector(model, img)
            for index, feat in enumerate(cls_score.data.cpu().numpy()):
#                 print(feat)
                n = sigmoid(float(feat[0]))
                b = sigmoid(float(feat[-1]))
#                 print(text, "%.8f" % (n/sum([n, b])), "%.8f" % (b/sum([n, b])))
                f.write(text + "%.8f" % (n/sum([n, b])) + os.linesep)

    path = '/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/validations/'
    for root, dirs, files in os.walk(os.path.abspath(path)):
        for file in files:
            img = mmcv.imread(path + file)
            if 'mask_head' in cfg.model.roi_head:
                result, a, cls_score, bbox_pred = inference_detector(model, img)
            else:
                result, cls_score, bbox_pred = inference_detector(model, img)
            for index, feat in enumerate(cls_score.data.cpu().numpy()):
#                 print(feat)
                n = sigmoid(float(feat[0]))
                b = sigmoid(float(feat[-1]))
#                 print(text, "%.8f" % (n/sum([n, b])), "%.8f" % (b/sum([n, b])))
                f.write(text + "%.8f" % (n/sum([n, b])) + os.linesep)

    path = '/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou/image/'
    for root, dirs, files in os.walk(os.path.abspath(path)):
        for file in files:
            img = mmcv.imread(path + file)
            if 'mask_head' in cfg.model.roi_head:
                result, a, cls_score, bbox_pred = inference_detector(model, img)
            else:
                result, cls_score, bbox_pred = inference_detector(model, img)
            for index, feat in enumerate(cls_score.data.cpu().numpy()):
#                 print(feat)
                n = sigmoid(float(feat[0]))
                b = sigmoid(float(feat[-1]))
#                 print(text, "%.8f" % (n/sum([n, b])), "%.8f" % (b/sum([n, b])))
                f.write(text + "%.8f" % (n/sum([n, b])) + os.linesep)
f.close()

/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/mmdet/apis/inference.py:41: UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '


loading annotations into memory...


/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools/coco.py:86: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/annotations/pseudo_images.json' mode='r' encoding='UTF-8'>
  dataset = json.load(open(annotation_file, 'r'))


Done (t=0.37s)
creating index...
index created!
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])


/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/mmdet/core/post_processing/bbox_nms.py:52: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629416375/work/torch/csrc/utils/python_arg_parser.cpp:766.)
  labels = valid_mask.nonzero()[:, 1]


(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Siz

True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([

(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Siz

(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Siz

(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Siz

(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Siz

(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Siz

tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], de

tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], de

True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([

tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Si

(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Siz

tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda

True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([

tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  

(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Siz

torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 10

True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([

True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([

(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Siz

(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])


/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_chenzhou.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/models/faster_rcnn_r50_fpn.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/datasets/chenzhou_instance.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/m

loading annotations into memory...


/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools/coco.py:86: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/annotations/pseudo_images.json' mode='r' encoding='UTF-8'>
  dataset = json.load(open(annotation_file, 'r'))


Done (t=0.51s)
creating index...
index created!


/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/mask_rcnn/mask_rcnn_r50_fpn_1x_chenzhou.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/models/mask_rcnn_r50_fpn.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/datasets/chenzhou_instance.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/ut

loading annotations into memory...


/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools/coco.py:86: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/annotations/pseudo_images.json' mode='r' encoding='UTF-8'>
  dataset = json.load(open(annotation_file, 'r'))


Done (t=0.48s)
creating index...
index created!


/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/ms_rcnn/ms_rcnn_r50_fpn_1x_chenzhou.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/mask_rcnn/mask_rcnn_r50_fpn_1x_chenzhou.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/models/mask_rcnn_r50_fpn.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/

loading annotations into memory...


/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools/coco.py:86: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/annotations/pseudo_images.json' mode='r' encoding='UTF-8'>
  dataset = json.load(open(annotation_file, 'r'))


Done (t=0.45s)
creating index...
index created!
