In [1]:
from mmdet.datasets import build_dataset
from mmdet.models import build_detector
from mmdet.apis import inference_detector, init_detector, show_result_pyplot
from mmcv import Config
import copy
import os.path as osp
import os
import mmcv
import numpy as np
import time
import cv2
import matplotlib.pyplot as plt
import matplotlib
from pylab import *
from matplotlib import cm

def draw_features(width, height, x, savedir, savename, i):
    print("{}/{}".format(savename,width*height))
    img = x
#     pmin = np.min(img)
#     pmax = np.max(img)
#     img = ((img - pmin) / (pmax - pmin + 0.000001))*255  #float在[0，1]之间，转换成0-255
    img = np.where(img, 255, 0)
    img=img.astype(np.uint8)  #转成unit8
#     img=cv2.applyColorMap(img, cv2.COLORMAP_JET) #生成heat map
#     img = img[:, :, ::-1]#注意cv2（BGR）和matplotlib(RGB)通道是相反的
    cv2.imwrite(savedir + '/' + str(i) + '/' + savename,mmcv.bgr2rgb(img),[int(cv2.IMWRITE_JPEG_QUALITY),95])

for i in range(1,15):
    os.environ["CUDA_VISIBLE_DEVICES"]="0"
    cfg = Config.fromfile('./configs/faster_rcnn/xiaohei_faster_rcnn_r50_fpn_1x_chenzhou.py')
    cfg.work_dir = 'logs/xiaohei_faster_rcnn_r50_fpn_1x_chenzhou_202011141101/'
    cfg.seed = 0
    cfg.total_epochs = 50
    cfg.log_config.interval = 1000

    checkpoint = cfg.work_dir + 'epoch_' + str(i) + '.pth'
    model = init_detector(cfg, checkpoint, device='cuda:0')
    datasets = [build_dataset(cfg.data.train)]
    model.CLASSES = datasets[0].CLASSES
    result_path = cfg.work_dir + '/tests/'
    if os.path.exists(result_path + "/result/" + str(i)) == False:
        os.makedirs(result_path + "/result/" + str(i))
    
    path = '/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/tests/'
    for root, dirs, files in os.walk(os.path.abspath(path)):
        for file in files:
#         file=files[0]
            img = mmcv.imread(path + file)
            result, x = inference_detector(model, img)
            img_np=x[0][0]
            draw_features(1, 1, img_np, result_path + '/result/', file, i)

    path = '/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/validations/'
    for root, dirs, files in os.walk(os.path.abspath(path)):
        for file in files:
#         file=files[0]
            img = mmcv.imread(path + file)
            result, x = inference_detector(model, img)
            img_np=x[0][0]
            draw_features(1, 1, img_np, result_path + '/result/', file, i)
            
# path = '/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou/image/'
# for root, dirs, files in os.walk(os.path.abspath(path)):
#     for file in files:
#         img = mmcv.imread(path + file)
#         result, x = inference_detector(model, img)
#         for index, feat in enumerate(x):
#             img_np=feat.data.cpu().numpy()
#             draw_features(16, 16, img_np, result_path + '/heatmap/' + str(index), file)

/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/mmdet/apis/inference.py:41: UserWarning: Class names are not saved in the checkpoint's meta data, use COCO classes by default.
  warnings.warn('Class names are not saved in the checkpoint\'s '


loading annotations into memory...


/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools/coco.py:86: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/annotations/pseudo_images.json' mode='r' encoding='UTF-8'>
  dataset = json.load(open(annotation_file, 'r'))


Done (t=0.38s)
creating index...
index created!
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_20235241120181012THY14920181012112622945T.jpg/1


/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/mmdet/core/post_processing/bbox_nms.py:52: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1595629416375/work/torch/csrc/utils/python_arg_parser.cpp:766.)
  labels = valid_mask.nonzero()[:, 1]


(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D1E1_134THY5720180831150957049T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_103THY4420180822155400562T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], devic

(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D2E1_121THY5220180830104301820T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D1E3_92THY3820180816095345993T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device

/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/faster_rcnn/xiaohei_faster_rcnn_r50_fpn_1x_chenzhou.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/models/xiaohei_faster_rcnn_r50_fpn.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/datasets/chenzhou_instance.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6

loading annotations into memory...


/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools/coco.py:86: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/annotations/pseudo_images.json' mode='r' encoding='UTF-8'>
  dataset = json.load(open(annotation_file, 'r'))


Done (t=0.38s)
creating index...
index created!
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_20235241120181012THY14920181012112622945T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D1E1_134THY5720180831150957049T.jpg/1
(768, 1024, 3)
True
(

A3B1C2D1E1_19305161420180913THY13820180913141631443V.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_19507361420181009THY14020181009143620711T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D2E1_121THY5220180830104301820T.jpg/1
(768, 1024

/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/faster_rcnn/xiaohei_faster_rcnn_r50_fpn_1x_chenzhou.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/models/xiaohei_faster_rcnn_r50_fpn.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/datasets/chenzhou_instance.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6

loading annotations into memory...


/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools/coco.py:86: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/annotations/pseudo_images.json' mode='r' encoding='UTF-8'>
  dataset = json.load(open(annotation_file, 'r'))


Done (t=0.39s)
creating index...
index created!
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_20235241120181012THY14920181012112622945T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D1E1_134THY5720180831150957049T.jpg/1
(768, 1024, 3)
True
(

(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_19507361420181009THY14020181009143620711T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D2E1_121THY5220180830104301820T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0

/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/faster_rcnn/xiaohei_faster_rcnn_r50_fpn_1x_chenzhou.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/models/xiaohei_faster_rcnn_r50_fpn.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/datasets/chenzhou_instance.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6

loading annotations into memory...


/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools/coco.py:86: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/annotations/pseudo_images.json' mode='r' encoding='UTF-8'>
  dataset = json.load(open(annotation_file, 'r'))


Done (t=0.32s)
creating index...
index created!
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_20235241120181012THY14920181012112622945T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D1E1_134THY5720180831150957049T.jpg/1
(768, 1024, 3)
True
(

A3B1C2D1E1_19305161420180913THY13820180913141631443V.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_19507361420181009THY14020181009143620711T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D2E1_121THY5220180830104301820T.jpg/1
(768, 1024

/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/faster_rcnn/xiaohei_faster_rcnn_r50_fpn_1x_chenzhou.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/models/xiaohei_faster_rcnn_r50_fpn.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/datasets/chenzhou_instance.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6

loading annotations into memory...


/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools/coco.py:86: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/annotations/pseudo_images.json' mode='r' encoding='UTF-8'>
  dataset = json.load(open(annotation_file, 'r'))


Done (t=0.28s)
creating index...
index created!
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_20235241120181012THY14920181012112622945T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D1E1_134THY5720180831150957049T.jpg/1
(768, 1024, 3)
True
(

(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_19507361420181009THY14020181009143620711T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D2E1_121THY5220180830104301820T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0

/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/faster_rcnn/xiaohei_faster_rcnn_r50_fpn_1x_chenzhou.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/models/xiaohei_faster_rcnn_r50_fpn.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/datasets/chenzhou_instance.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6

loading annotations into memory...


/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools/coco.py:86: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/annotations/pseudo_images.json' mode='r' encoding='UTF-8'>
  dataset = json.load(open(annotation_file, 'r'))


Done (t=0.28s)
creating index...
index created!
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_20235241120181012THY14920181012112622945T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D1E1_134THY5720180831150957049T.jpg/1
(768, 1024, 3)
True
(

(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_19507361420181009THY14020181009143620711T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D2E1_121THY5220180830104301820T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0

/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/faster_rcnn/xiaohei_faster_rcnn_r50_fpn_1x_chenzhou.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/models/xiaohei_faster_rcnn_r50_fpn.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/datasets/chenzhou_instance.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6

loading annotations into memory...


/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools/coco.py:86: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/annotations/pseudo_images.json' mode='r' encoding='UTF-8'>
  dataset = json.load(open(annotation_file, 'r'))


Done (t=0.26s)
creating index...
index created!
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_20235241120181012THY14920181012112622945T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D1E1_134THY5720180831150957049T.jpg/1
(768, 1024, 3)
True
(

(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_19507361420181009THY14020181009143620711T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D2E1_121THY5220180830104301820T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0

/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/faster_rcnn/xiaohei_faster_rcnn_r50_fpn_1x_chenzhou.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/models/xiaohei_faster_rcnn_r50_fpn.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/datasets/chenzhou_instance.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6

loading annotations into memory...


/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools/coco.py:86: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/annotations/pseudo_images.json' mode='r' encoding='UTF-8'>
  dataset = json.load(open(annotation_file, 'r'))


Done (t=0.29s)
creating index...
index created!
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_20235241120181012THY14920181012112622945T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D1E1_134THY5720180831150957049T.jpg/1
(768, 1024, 3)
True
(

A3B1C2D1E1_19305161420180913THY13820180913141631443V.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_19507361420181009THY14020181009143620711T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D2E1_121THY5220180830104301820T.jpg/1
(768, 1024

/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/faster_rcnn/xiaohei_faster_rcnn_r50_fpn_1x_chenzhou.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/models/xiaohei_faster_rcnn_r50_fpn.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/datasets/chenzhou_instance.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6

loading annotations into memory...


/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools/coco.py:86: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/annotations/pseudo_images.json' mode='r' encoding='UTF-8'>
  dataset = json.load(open(annotation_file, 'r'))


Done (t=0.42s)
creating index...
index created!
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_20235241120181012THY14920181012112622945T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D1E1_134THY5720180831150957049T.jpg/1
(768, 1024, 3)
True
(

tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A3B1C2D1E1_19305161420180913THY13820180913141631443V.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_19507361420181009THY14020181009143620711T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size

/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/faster_rcnn/xiaohei_faster_rcnn_r50_fpn_1x_chenzhou.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/models/xiaohei_faster_rcnn_r50_fpn.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/datasets/chenzhou_instance.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6

loading annotations into memory...


/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools/coco.py:86: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/annotations/pseudo_images.json' mode='r' encoding='UTF-8'>
  dataset = json.load(open(annotation_file, 'r'))


Done (t=0.39s)
creating index...
index created!
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_20235241120181012THY14920181012112622945T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D1E1_134THY5720180831150957049T.jpg/1
(768, 1024, 3)
True
(

A3B1C2D1E1_19305161420180913THY13820180913141631443V.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_19507361420181009THY14020181009143620711T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D2E1_121THY5220180830104301820T.jpg/1
(768, 1024

/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/faster_rcnn/xiaohei_faster_rcnn_r50_fpn_1x_chenzhou.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/models/xiaohei_faster_rcnn_r50_fpn.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/datasets/chenzhou_instance.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6

loading annotations into memory...


/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools/coco.py:86: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/annotations/pseudo_images.json' mode='r' encoding='UTF-8'>
  dataset = json.load(open(annotation_file, 'r'))


Done (t=0.41s)
creating index...
index created!
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_20235241120181012THY14920181012112622945T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D1E1_134THY5720180831150957049T.jpg/1
(768, 1024, 3)
True
(

(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_19507361420181009THY14020181009143620711T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D2E1_121THY5220180830104301820T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0

/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/faster_rcnn/xiaohei_faster_rcnn_r50_fpn_1x_chenzhou.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/models/xiaohei_faster_rcnn_r50_fpn.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/datasets/chenzhou_instance.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6

loading annotations into memory...


/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools/coco.py:86: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/annotations/pseudo_images.json' mode='r' encoding='UTF-8'>
  dataset = json.load(open(annotation_file, 'r'))


Done (t=0.38s)
creating index...
index created!
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_20235241120181012THY14920181012112622945T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D1E1_134THY5720180831150957049T.jpg/1
(768, 1024, 3)
True
(

A3B1C2D1E1_19305161420180913THY13820180913141631443V.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_19507361420181009THY14020181009143620711T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D2E1_121THY5220180830104301820T.jpg/1
(768, 1024

/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/faster_rcnn/xiaohei_faster_rcnn_r50_fpn_1x_chenzhou.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/models/xiaohei_faster_rcnn_r50_fpn.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/datasets/chenzhou_instance.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6

loading annotations into memory...


/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools/coco.py:86: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/annotations/pseudo_images.json' mode='r' encoding='UTF-8'>
  dataset = json.load(open(annotation_file, 'r'))


Done (t=0.39s)
creating index...
index created!
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_20235241120181012THY14920181012112622945T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D1E1_134THY5720180831150957049T.jpg/1
(768, 1024, 3)
True
(

(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_19507361420181009THY14020181009143620711T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D2E1_121THY5220180830104301820T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0

/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/faster_rcnn/xiaohei_faster_rcnn_r50_fpn_1x_chenzhou.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/models/xiaohei_faster_rcnn_r50_fpn.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/mmcv/utils/config.py:110: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/code/mmdetection/configs/_base_/datasets/chenzhou_instance.py' mode='r' encoding='UTF-8'>
  config_file = open(filename).read()
/root/miniconda3/envs/mmdetection/lib/python3.6

loading annotations into memory...


/root/miniconda3/envs/mmdetection/lib/python3.6/site-packages/pycocotools/coco.py:86: ResourceWarning: unclosed file <_io.TextIOWrapper name='/root/workspace/Thyroid_Solid_Nodule/data/preprocess/chenzhou_aug/annotations/pseudo_images.json' mode='r' encoding='UTF-8'>
  dataset = json.load(open(annotation_file, 'r'))


Done (t=0.38s)
creating index...
index created!
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_20235241120181012THY14920181012112622945T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D1E1_134THY5720180831150957049T.jpg/1
(768, 1024, 3)
True
(

(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C2D1E1_19507361420181009THY14020181009143620711T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([[1024,    0,    0,  768]], device='cuda:0', dtype=torch.int32)
torch.Size([1, 4])
tensor([0], device='cuda:0')
torch.Size([1])
tensor([1., 1., 1., 1.], device='cuda:0')
1
torch.Size([1, 768, 1024])
torch.Size([1, 1, 384, 512])
A4B1C3D2E1_121THY5220180830104301820T.jpg/1
(768, 1024, 3)
True
(768, 1024, 3)
768 1024
tensor([[1024,    0,    0